added timing test sort

diff --git a/testing/Makefile b/testing/Makefile
--- a/testing/Makefile
+++ b/testing/Makefile
@@ -18,13 +18,48 @@ coverage:
 		sed -i -e 's|>/[^<>]*/wield/|>wield/|' test_results/coverage/*.html
 		sed -i -e 's|>/[^<>]*/gwinc/|>gwinc/|' test_results/coverage/*.html
 
+timing:
+		printf "" > timing.txt;
+		for F in test_results/reports/all/*.html; do \
+			FNAME=$$(basename $$F); \
+			TIMING="$${FNAME%.html} $$(sed -n -e 's/^.*ran in \([0-9]\+.*[0-9]\+\) seconds.*$$/\1/p' $$F)"; \
+			echo $$TIMING;\
+			echo $$TIMING >> timing.txt;\
+		done
+		sort -k 2n timing.txt -o timing.txt;
+		# remove the timing column
+		awk '{print $$1}' timing.txt > timing_sort.txt
 
 TESTS = $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt 2> /dev/null)
 
-$(TESTS): %: test_results/reports/%.html
+# remove all for it to not re-build failed tests
+$(TESTS): %: test_results/reports/all/%.html
 		@echo $*
 
 test_results/reports/%.html: pytest-collection.txt
+		$(eval FILE := $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt $*))
+		$(eval PREHTML := test_results/reports/inprogress/$*.html)
+		-mkdir -p test_results/reports/inprogress
+		ln --force -T -s ../assets test_results/reports/inprogress/assets;
+		-mkdir -p test_results/reports/assets
+		-mkdir -p test_results/reports/coverage
+		#-pytest $(FILE) --ws-skip-slow --html=$(PREHTML)
+		# This long command runs the specific pytest and generates a coverage file
+		coverage run --source=wield --source=gwinc --branch --context=$* --data-file=test_results/reports/coverage/$* -m pytest -c 'pytest.ini' --rootdir='.' $(FILE) --ws-skip-slow --html=$(PREHTML)
+		if [ "$$?" -eq 0 ]; \
+    then \
+			mv $(PREHTML) $@; \
+			ln --force -T -s ../$*.html test_results/reports/all/$*.html; \
+		else\
+			mkdir -p test_results/reports/failed; \
+			mkdir -p test_results/reports/all; \
+			ln --force -T -s ../assets test_results/reports/failed/assets; \
+			mv $(PREHTML) test_results/reports/failed/; \
+			ln --force -T -s ../failed/$*.html test_results/reports/all/$*.html; \
+			false; \
+    fi
+
+test_results/reports/all/%.html: test_results/reports/%.html
 		$(eval FILE := $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt $*))
 		$(eval PREHTML := test_results/reports/inprogress/$*.html)
 		-mkdir -p test_results/reports/inprogress
