fixing up

diff --git a/testing/Makefile b/testing/Makefile
--- a/testing/Makefile
+++ b/testing/Makefile
@@ -30,36 +30,37 @@ timing:
 		# remove the timing column
 		awk '{print $$1}' timing.txt > timing_sort.txt
 
-TESTS = $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt 2> /dev/null)
+TESTS = $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt --sort timing_sort.txt 2> /dev/null)
 
 # remove all for it to not re-build failed tests
 $(TESTS): %: test_results/reports/all/%.html
 		@echo $*
 
-test_results/reports/%.html: pytest-collection.txt
-		$(eval FILE := $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt $*))
-		$(eval PREHTML := test_results/reports/inprogress/$*.html)
-		-mkdir -p test_results/reports/inprogress
-		ln --force -T -s ../assets test_results/reports/inprogress/assets;
-		-mkdir -p test_results/reports/assets
-		-mkdir -p test_results/reports/coverage
-		#-pytest $(FILE) --ws-skip-slow --html=$(PREHTML)
-		# This long command runs the specific pytest and generates a coverage file
-		coverage run --source=wield --source=gwinc --branch --context=$* --data-file=test_results/reports/coverage/$* -m pytest -c 'pytest.ini' --rootdir='.' $(FILE) --ws-skip-slow --html=$(PREHTML)
-		if [ "$$?" -eq 0 ]; \
-    then \
-			mv $(PREHTML) $@; \
-			ln --force -T -s ../$*.html test_results/reports/all/$*.html; \
-		else\
-			mkdir -p test_results/reports/failed; \
-			mkdir -p test_results/reports/all; \
-			ln --force -T -s ../assets test_results/reports/failed/assets; \
-			mv $(PREHTML) test_results/reports/failed/; \
-			ln --force -T -s ../failed/$*.html test_results/reports/all/$*.html; \
-			false; \
-    fi
+# test_results/reports/%.html: pytest-collection.txt
+# 		$(eval FILE := $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt $*))
+# 		$(eval PREHTML := test_results/reports/inprogress/$*.html)
+# 		-mkdir -p test_results/reports/inprogress
+# 		ln --force -T -s ../assets test_results/reports/inprogress/assets;
+# 		-mkdir -p test_results/reports/assets
+# 		-mkdir -p test_results/reports/coverage
+# 		#-pytest $(FILE) --ws-skip-slow --html=$(PREHTML)
+# 		# This long command runs the specific pytest and generates a coverage file
+# 		coverage run --source=gwinc,wield --branch --context=$* --data-file=test_results/reports/coverage/$* -m pytest -c 'pytest.ini' --rootdir='.' $(FILE) --ws-skip-slow --html=$(PREHTML)
+# 		if [ "$$?" -eq 0 ]; \
+#     then \
+# 			mv $(PREHTML) $@; \
+# 			ln --force -T -s ../$*.html test_results/reports/all/$*.html; \
+#       ln --force -T -s ../assets test_results/reports/all/assets; \
+# 		else\
+# 			mkdir -p test_results/reports/failed; \
+# 			mkdir -p test_results/reports/all; \
+# 			ln --force -T -s ../assets test_results/reports/failed/assets; \
+# 			mv $(PREHTML) test_results/reports/failed/; \
+# 			ln --force -T -s ../failed/$*.html test_results/reports/all/$*.html; \
+# 			false; \
+#     fi
 
-test_results/reports/all/%.html: test_results/reports/%.html
+test_results/reports/all/%.html:  pytest-collection.txt
 		$(eval FILE := $(shell python3 -m wield.pytest.parse_collection pytest-collection.txt $*))
 		$(eval PREHTML := test_results/reports/inprogress/$*.html)
 		-mkdir -p test_results/reports/inprogress
@@ -68,11 +69,12 @@ test_results/reports/all/%.html: test_results/reports/%.html
 		-mkdir -p test_results/reports/coverage
 		#-pytest $(FILE) --ws-skip-slow --html=$(PREHTML)
 		# This long command runs the specific pytest and generates a coverage file
-		coverage run --source=wield --source=gwinc --branch --context=$* --data-file=test_results/reports/coverage/$* -m pytest -c 'pytest.ini' --rootdir='.' $(FILE) --ws-skip-slow --html=$(PREHTML)
+		coverage run --source=gwinc,wield --branch --context=$* --data-file=test_results/reports/coverage/$* -m pytest -c 'pytest.ini' --rootdir='.' $(FILE) --ws-skip-slow --html=$(PREHTML)
 		if [ "$$?" -eq 0 ]; \
     then \
 			mv $(PREHTML) $@; \
 			ln --force -T -s ../$*.html test_results/reports/all/$*.html; \
+			ln --force -T -s ../assets test_results/reports/all/assets; \
 		else\
 			mkdir -p test_results/reports/failed; \
 			mkdir -p test_results/reports/all; \
